"""empty message

Revision ID: 46534780c0a1
Revises: 4d6ac076bd5e
Create Date: 2021-10-31 21:58:59.600773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46534780c0a1'
down_revision = '4d6ac076bd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('path', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'path')
    # ### end Alembic commands ###
