"""added referral

Revision ID: aaf9543d8db0
Revises: 222203e86366
Create Date: 2022-08-21 08:11:18.724346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf9543d8db0'
down_revision = '222203e86366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referee', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_referee'), 'users', ['referee'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['referee'], ['id'])
    op.drop_column('users', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('path', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_referee'), table_name='users')
    op.drop_column('users', 'referee')
    # ### end Alembic commands ###
